#ifndef __YARNS_CONFIG__
#define __YARNS_CONFIG__

#define YARNS_STACK_PAGES 4
#define YARNS_ENABLE_SMP
// in µs
#define YARNS_DEAD_SLEEP_TIME 50

// schedulers
#define YARNS_SCHED_MULTILEVEL 1
#define YARNS_SCHED_ROUND_ROBIN 2
#define YARNS_SCHED_RANDOM 3
#define YARNS_SCHED_RB 4
#define YARNS_SCHEDULER YARNS_SCHED_RB
// in µs
#define YARNS_TIMESLICE 10

// target
#define YARNS_TARGET_MACH 1
#define YARNS_TARGET_LINUX 2
#define YARNS_SELECTED_TARGET YARNS_TARGET_MACH
#define YARNS_USE_SYSTEM_ALLOCATOR

// maxima
#define YARNS_MAX_PROCESSES 65536

// overrides
//#define YARNS_OVERRIDE_CORE_COUNT 16

#endif
