#!/usr/bin/env php
<?php

$argv0 = array_shift($argv);

if (count($argv) == 0 || count($argv) == 1)
{
	echo "Usage: $argv0 base-config arches\n";
	exit(1);
}

$base = array_shift($argv);
$arches = $argv;
$lipoes = array();

function shell ( $command )
{
	echo "$command\n";
	system($command);
}

foreach ($arches as $arch)
{
	shell("./make-profile $base-$arch");
	shell("make clean");
	shell("make -j2 libyarns.a");
	shell("mv libyarns.a libyarns-$arch.a");
	$lipoes[] = "libyarns-$arch.a";
}

shell("lipo -create -output libyarns.a " . implode(' ', $lipoes));
shell("rm -i " . implode(' ', $lipoes));
